services:
   web:
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - ALLOW_OVERRIDE=true
      ports:
        - "81:80"
        - "443:443"
      links:
        - db
      volumes:
        - ./app:/var/www/html/
        - ./certs:/etc/apache2/ssl
        - ./generate-certs.sh:/usr/local/bin/generate-certs.sh
      command: ["/bin/sh", "-c", "/usr/local/bin/generate-certs.sh"]

   db:
     image: mariadb:12.0.2
     restart: always
     volumes:
       - ./mysql:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWD}
       MYSQL_DATABASE: ${MYSQL_DB}
     ports:
       - "8889:3306"

   phpmyadmin:
     image: phpmyadmin/phpmyadmin:latest
     links:
       - db
     ports:
       - 8890:80
     environment:
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWD}
       MYSQL_DATABASE: ${MYSQL_DB}
